export enum RoleNombre {
  ADMIN = 'ADMIN',
  CLIENTE = 'CLIENTE'
}

export enum Disponibilidad {
  DISPONIBLE = 'DISPONIBLE',
  OCUPADO = 'OCUPADO',
  AUSENTE = 'AUSENTE',
  INACTIVO = 'INACTIVO'
}

export enum EstadoOrden {
  PENDIENTE = 'PENDIENTE',
  RECIBIDO = 'RECIBIDO',
  EN_PREPARACION = 'EN_PREPARACION',
  LISTO = 'LISTO',
  EN_CAMINO = 'EN_CAMINO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO'
}

export enum MetodoPago {
  EFECTIVO = 'EFECTIVO',
  TARJETA = 'TARJETA',
  SINPE_MOVIL = 'SINPE_MOVIL'
}

export enum TipoPedido {
  COMER_AQUI = 'COMER_AQUI',
  PARA_LLEVAR = 'PARA_LLEVAR',
  DELIVERY = 'DELIVERY'
}

export enum TipoNotificacion {
  NUEVA_ORDEN = 'NUEVA_ORDEN',
  ORDEN_LISTA = 'ORDEN_LISTA',
  CAMBIO_ESTADO = 'CAMBIO_ESTADO',
  MENSAJE = 'MENSAJE',
  RECORDATORIO = 'RECORDATORIO',
  INICIO_SESION = 'INICIO_SESION'
}

export enum EstadoNotificacion {
  NO_LEIDA = 'NO_LEIDA',
  LEIDA = 'LEIDA'
}

export enum TipoHistorial {
  CAMBIO_ESTADO = 'CAMBIO_ESTADO',
  COMENTARIO_CLIENTE = 'COMENTARIO_CLIENTE'
}
